### PR TITLE
fix: daemon and cid optimizations

### LINKED ISSUE #25: Bug: Error when IPFS-desktop is running `bind: address already in use`
```bash
npx -p @ipfs-shipyard/pinning-service-compliance@0.0.2 -- pinning-service-compliance -s $PINATA_API_ENDPOINT $PINATA_API_TOKEN
Request with no authentication token
        ✓ Response object matches api spec schema
        ✘ Returns a 403
Request with invalid token
        ✓ Response object matches api spec schema
        ✘ Returns a 403
2022-04-21T23:24:12.016Z [error] : Problem running compliance check: 'addPin': Error: Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
 

 Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use 

 Command failed with exit code 1: node_modules/.bin/ipfs daemon
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
 


2022-04-21T23:24:14.707Z [error] : Problem running compliance check: 'deleteNewPin': Error: Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
 

 Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use 

 Command failed with exit code 1: node_modules/.bin/ipfs daemon
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
 


List pin objects (GET /pins) in all states
        ✓ Response object matches api spec schema
        ✓ Response is successful
        ✓ Response statusCode is 200
2022-04-21T23:24:17.853Z [error] : Problem running compliance check: 'replacePin': Error: Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
 

 Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use 

 Command failed with exit code 1: node_modules/.bin/ipfs daemon
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
 


2022-04-21T23:24:20.722Z [error] : Problem running compliance check: 'matchPin': Error: Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
 

 Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use 

 Command failed with exit code 1: node_modules/.bin/ipfs daemon
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
 


Get all pins
        ✓ Response is ok
        ✓ Result is not null
2022-04-21T23:24:23.688Z [error] : Problem running compliance check: 'testPagination': Error: Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
 

 Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use 

 Command failed with exit code 1: node_modules/.bin/ipfs daemon
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
Initializing daemon...
go-ipfs version: 0.12.1
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.227/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.227/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
```

### PR DESCRIPTION
**Pull request by SgtPooki**
fixes #25

### CODE REVIEW

File: src/utils/getIpfsClient.ts [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+
+    if (daemonIsRunningAlready) {
+      return {
+        client: client as InlineableClient,
+        done
+      }
+    }
+  } catch (err) {
+    logger.debug('Could not use IPFSHTTPClient', err)
+  }
```
Comment (lidel) [inline src/utils/getIpfsClient.ts:56]: We should not use default daemon/port in tests, these tests were always a headache to maintain and debug because of unexpected side-effects.

Other test suites like sharness in go-ipfs or https://github.com/ipfs/interop  use ephemeral node spawned on random ports.

```suggestion
```

File: src/utils/getIpfsClient.ts [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+  try {
+    logger.debug('Attempting to use ipfsd-ctl to create a client')
+    // no daemon currently running, start one
+    const ipfsd = await Ctl.createController({
+      ipfsHttpModule: ipfsHttpClient,
+      ipfsBin: join('node_modules', '.bin', 'ipfs')
+    })
```
Comment (lidel) [inline src/utils/getIpfsClient.ts:64]: Tests should always spawn a clean, `disposable` and `test` instance.

See https://github.com/ipfs-shipyard/pinning-service-compliance/issues/25#issuecomment-1108838708

**Review by lidel — CHANGES_REQUESTED** [review]
- Inline CIDs creation can be done in pure JS – see comment inline
- Avoid reusing daemon if present – tests should use a clean, controlled instance (especially when we will use it for bitswap / DHT tests)

File: src/utils/getIpfsClient.ts (hunk 1 above)
Comment (SgtPooki) [reply src/utils/getIpfsClient.ts:56]: Can you link me to an example for creating an ephemeral daemon?

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,12 @@
+## [0.0.3](https://github.com/ipfs-shipyard/pinning-service-compliance/compare/v0.0.2...v0.0.3) (2022-04-25)
```
Comment (achingbrain) [inline CHANGELOG.md:1]: Was this change intentional?

File: package.json [hunk 4]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "@ipfs-shipyard/pinning-service-compliance",
-  "version": "0.0.2",
+  "version": "0.0.3",
```
Comment (achingbrain) [inline package.json:3]: Was this change intentional?

File: src/utils/getInlineCid.ts [hunk 5]
```diff
@@ -1,20 +1,23 @@
...
+  try {
+    const inlineDateDigest = await identity.digest(inlineUint8Array)
+    try {
+      return CID.createV1(identity.code, inlineDateDigest).toString()
+    } catch (err) {
+      logger.error('Problem creating an inline CID', err)
+      throw err
+    }
+  } catch (err) {
+    logger.error('Could not get an ipfs client', err)
```
Comment (achingbrain) [inline src/utils/getInlineCid.ts:18]: The double-catch here means if `CID.createV1` throws, you'll get `'Problem creating an inline CID'` and then `'Could not get an ipfs client'` as well in the logs.  Might be clearer to remove the nesting and just have one error log line for one error?

File: src/utils/getIpfsClient.ts [hunk 6]
```diff
@@ -0,0 +1,43 @@
+import { join } from 'path'
```
Comment (achingbrain) [inline src/utils/getIpfsClient.ts:1]: Is the export from this file used anywhere or can the whole thing be removed?

File: tsconfig.json [hunk 7]
```diff
@@ -21,7 +21,7 @@
       "dom",
       "dom.iterable"
     ],
-    "types": ["@ipfs-shipyard/pinning-service-client", "node"],
+    "types": ["@ipfs-shipyard/pinning-service-client", "node", "multiformats"],
```
Comment (achingbrain) [inline tsconfig.json:24]: This adds the `multiformats` types [to the global scope](https://www.typescriptlang.org/tsconfig#types), do we want that?

**Review by achingbrain — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 3 above)
Comment (SgtPooki) [reply CHANGELOG.md:1]: kind of. this was made my aegir when doing an npm release in order to test running the compliance checker from npm. Obviously, those are just testing releases, but I didn't think doing release candidates pre-v1 for a newly launched tool was necessary. Feel free to educate me :)

File: src/utils/getInlineCid.ts (hunk 5 above)
Comment (SgtPooki) [reply src/utils/getInlineCid.ts:18]: absolutely.

File: src/utils/getIpfsClient.ts (hunk 6 above)
Comment (SgtPooki) [reply src/utils/getIpfsClient.ts:1]: this will be used in the future for other compliance checks. It's not currently being used though, since we switched to using multiformats for inlineCID creation

File: tsconfig.json (hunk 7 above)
Comment (SgtPooki) [reply tsconfig.json:24]: nope! thanks.

File: src/utils/getInlineCid.ts (hunk 5 above)
Comment (SgtPooki) [reply src/utils/getInlineCid.ts]: https://github.com/ipfs-shipyard/pinning-service-compliance/pull/28/commits/23c71997b491bcf5f822a1c5fc55c55e68b04cb8

File: package.json (hunk 4 above)
Comment (SgtPooki) [reply package.json:3]: this was done to test npx usage was still working correctly. If there is a better recommended practice I should be following for this situation, please let me know

**Review by SgtPooki — COMMENTED** [review]
No review for a while, I'm going to merge and we can discuss later if necessary.
