### PR TITLE
fix: Compliance check sum is consistent for all services

### LINKED ISSUE #29: Bug: Summary compliance check SUM is not consistent between service runs
## Problem

Testing 4 different pinning services, we end up with the following summary lines:

* Summary (21/25 successful)
* Summary (5/15 successful)
* Summary (9/20 successful)
* Summary (18/26 successful)

## Details

The total compliance checks ran should ALWAYS be the same. If one errors, it should show in the final results and summary.

**Each of the above lines should show the same denominator; always**

### More output

```bash
> npm start -- -d -s $PINATA_API_ENDPOINT $PINATA_API_TOKEN
npm start -- -d -s $WEB3_API_ENDPOINT $WEB3_API_TOKEN
npm start -- -d -s $NFT_API_ENDPOINT $NFT_API_TOKEN
npm start -- -d -s $ESTUARY_API_ENDPOINT $ESTUARY_API_TOKEN

> @ipfs-shipyard/pinning-service-compliance@0.0.3 start

https://api.pinata.cloud/psa compliance:

Summary (21/25 successful)

  ✘ Request with no authentication token
  ✘ Request with invalid token
  ✓ Pins post of CID 'bafkqadjrgy2tcmbvgi3tcnjtgiya'
  ✘ Can create and then delete a new pin
  ✓ List pin objects (GET /pins) in all states
  ✓ Can create and replace a pin's CID
  ✓ Can create a pin with name='32c1af99-ff7e-402f-9846-c56e6f30cde5'
  ✓ Can retrieve pin with name '32c1af99-ff7e-402f-9846-c56e6f30cde5' via the 'exact' TextMatchingStrategy
  ✓ Can retrieve pin with name '32C1AF99-FF7E-402F-9846-C56E6F30CDE5' via the 'iexact' TextMatchingStrategy
  ✓ Can retrieve pin with name 'ff7e-402f-9846-c56' via the 'partial' TextMatchingStrategy
  ✓ Can retrieve pin with name 'FF7E-402F-9846-C56' via the 'ipartial' TextMatchingStrategy
  ✓ Get all pins
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi3tqnrsguza'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi3tsmjyhezq'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi3tsnzugaza'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi4damrqga3q'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi4danrzgmya'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi4dcmjzg4zq'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi4dcnrzgq2a'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi4demrqgyza'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi4denrygqyq'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgi4dgmjyga4q'
  ✓ First page of pins
  ✓ Retrieve the next page of pins
  ✘ Can delete all pins


See the full report at /Users/sgtpooki/code/work/protocol.ai/ipfs/pinning-service-compliance/pinning-service-compliance/docs/api.pinata.cloud.md

> @ipfs-shipyard/pinning-service-compliance@0.0.3 start

...

https://api.web3.storage compliance:

Summary (5/15 successful)

  ✘ Request with no authentication token
  ✘ Request with invalid token
  ✘ Pins post of CID 'bafkqadjrgy2tcmbvgi4tgmzygi3q'
  ✘ Can create and then delete a new pin
  ✘ List pin objects (GET /pins) in all states
  ✓ Can create and replace a pin's CID
  ✓ Can create a pin with name='3596f170-5ed2-43e8-bd41-e1f21a6a22fa'
  ✘ Can retrieve pin with name '3596f170-5ed2-43e8-bd41-e1f21a6a22fa' via the 'exact' TextMatchingStrategy
  ✘ Can retrieve pin with name '3596F170-5ED2-43E8-BD41-E1F21A6A22FA' via the 'iexact' TextMatchingStrategy
  ✘ Can retrieve pin with name '5ed2-43e8-bd41-e1f' via the 'partial' TextMatchingStrategy
  ✘ Can retrieve pin with name '5ED2-43E8-BD41-E1F' via the 'ipartial' TextMatchingStrategy
  ✓ Get all pins
  ✓ First page of pins
  ✘ Retrieve the next page of pins
  ✓ Can delete all pins


See the full report at /Users/sgtpooki/code/work/protocol.ai/ipfs/pinning-service-compliance/pinning-service-compliance/docs/api.web3.storage.md

> @ipfs-shipyard/pinning-service-compliance@0.0.3 start

...

https://nft.storage/api compliance:

Summary (9/20 successful)

  ✘ Request with no authentication token
  ✘ Request with invalid token
  ✘ Pins post of CID 'bafkqadjrgy2tcmbvgmydambvha2q'
  ✓ Can create and then delete a new pin
  ✘ List pin objects (GET /pins) in all states
  ✓ Can create and replace a pin's CID
  ✓ Can create a pin with name='9e2ec2c7-25a5-4316-8285-2f33aa0ecebf'
  ✘ Can retrieve pin with name '9e2ec2c7-25a5-4316-8285-2f33aa0ecebf' via the 'exact' TextMatchingStrategy
  ✘ Can retrieve pin with name '9E2EC2C7-25A5-4316-8285-2F33AA0ECEBF' via the 'iexact' TextMatchingStrategy
  ✘ Can retrieve pin with name '25a5-4316-8285-2f3' via the 'partial' TextMatchingStrategy
  ✘ Can retrieve pin with name '25A5-4316-8285-2F3' via the 'ipartial' TextMatchingStrategy
  ✓ Get all pins
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmydgnztge2a'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmydimjvgm2q'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmydinjygq4q'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmydkmjsgazq'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmydknjxgq2a'
  ✘ First page of pins
  ✘ Retrieve the next page of pins
  ✘ Can delete all pins


See the full report at /Users/sgtpooki/code/work/protocol.ai/ipfs/pinning-service-compliance/pinning-service-compliance/docs/nft.storage.md

> @ipfs-shipyard/pinning-service-compliance@0.0.3 start

...

https://api.estuary.tech/pinning compliance:

Summary (18/26 successful)

  ✘ Request with no authentication token
  ✘ Request with invalid token
  ✘ Pins post of CID 'bafkqadjrgy2tcmbvgmydqmbqge4a'
  ✘ Can create and then delete a new pin
  ✘ List pin objects (GET /pins) in all states
  ✘ Can create and replace a pin's CID
  ✓ Can create a pin with name='16ecf9ed-a0b1-4841-a5d3-6225954f0943'
  ✓ Can retrieve pin with name '16ecf9ed-a0b1-4841-a5d3-6225954f0943' via the 'exact' TextMatchingStrategy
  ✓ Can retrieve pin with name '16ECF9ED-A0B1-4841-A5D3-6225954F0943' via the 'iexact' TextMatchingStrategy
  ✓ Can retrieve pin with name 'a0b1-4841-a5d3-622' via the 'partial' TextMatchingStrategy
  ✓ Can retrieve pin with name 'A0B1-4841-A5D3-622' via the 'ipartial' TextMatchingStrategy
  ✓ Get all pins
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytanrxg42a'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytaojzga3a'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytcmzsge3q'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytcnrvgu2a'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytcojzha3a'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytemzugi3q'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytenrwg4ya'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytgmbrha4q'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytgmzvgiyq'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytgnzqgiyq'
  ✓ Can create new pin for testing pagination cid='bafkqadjrgy2tcmbvgmytimbvge2q'
  ✘ First page of pins
  ✓ Retrieve the next page of pins
  ✘ Can delete all pins


See the full report at /Users/sgtpooki/code/work/protocol.ai/ipfs/pinning-service-compliance/pinning-service-compliance/docs/api.estuary.tech.md

```

##

### PR DESCRIPTION
**Pull request by SgtPooki**
fix #29

### CODE REVIEW

File: src/clientFromServiceAndTokenPair.ts [hunk 1]
```diff
@@ -1,12 +1,30 @@
...
 
 function clientFromServiceAndTokenPair ([endpointUrl, accessToken]: ServiceAndTokenPair, middleWareOptions: RequestResponseLoggerOptions): RemotePinningServiceClient {
-  const config = new Configuration({
+  const config = new (Configuration as typeof NodeFetch.Configuration)({
     endpointUrl,
     accessToken,
+    fetchApi: async (url: RequestInfo, init?: RequestInit) => {
+      return await fetch(url, {
+        ...init,
+        highWaterMark: 1024 * 1024 * 2
```
Comment (SgtPooki) [inline src/clientFromServiceAndTokenPair.ts:17]: This line fixes an issue where node-fetch silently crashes node when large responses are received.

File: package.json [hunk 2]
```diff
@@ -121,42 +121,45 @@
...
-    "marked": "^4.0.12",
+    "ipfs": "^0.62.3",
+    "ipfs-core": "^0.14.3",
+    "ipfs-http-client": "^56.0.3",
+    "ipfsd-ctl": "^11.0.0",
+    "marked": "^4.0.16",
     "marked-terminal": "^5.1.1",
-    "multiformats": "^9.6.4",
+    "multiformats": "^9.6.5",
+    "node-fetch": "^3.2.4",
```
Comment (achingbrain) [inline package.json:157]: `node-fetch` is full of bugs.  Did you consider using [undici](https://www.npmjs.com/package/undici) which is going to be released as part of node pretty soon and probably has different bugs?

File: src/checks/edit/replacePin.ts [hunk 3]
```diff
@@ -26,12 +23,24 @@ const replacePin = async (pair: ServiceAndTokenPair) => {
...
   createPinApiCall.expect({
     title: `Could obtain requestid from new pin (${requestid})`,
-    fn: () => requestid != null
+    fn: () => requestid != null && requestid !== 'null'
   })
 
+  let newCid = await getInlineCid()
+  let delay = 1000
+  /**
+   * If we run too fast, the timestamp returned ends up generating the same CID
```
Comment (achingbrain) [inline src/checks/edit/replacePin.ts:36]: I think this is because `getInlineCid` takes a string `value` that defaults to the current timestamp in ms as a string - you could use `process.hrtime()` or a random number generator or something instead and not need the delay?

File: package.json [hunk 4]
```diff
@@ -121,42 +121,45 @@
     "test": "aegir lint",
     "build": "aegir build",
     "start": "node dist/src/index.js",
-    "release": "npm run build && aegir release --test false --docs false"
+    "dev-start": "NODE_OPTIONS='--unhandled-rejections=strict --trace-atomics-wait --trace-deprecation --trace-exit --trace-sigint --trace-uncaught --trace-warnings' ts-node-esm --esm -T --preferTsExts --logError src/index.ts",
+    "release": "npm run build && aegir release --test false --docs false",
```
Comment (achingbrain) [inline package.json:125]: Aegir doesn't run tests or generate docs on release any more.

```suggestion
    "release": "npm run build && aegir release",
```

File: package.json (hunk 2 above)
Comment (SgtPooki) [reply package.json:157]: I did.. but I have already got it all working with node-fetch, so I can explore that later. Opened https://github.com/ipfs-shipyard/pinning-service-compliance/issues/57

File: src/ApiCall.ts [hunk 5]
```diff
@@ -57,56 +62,69 @@ class ApiCall<T> {
...
+      } catch (err) {
+        const error = isError(err) ? err : new Error(err as string)
+        this.errors.push({
+          title: 'Error running primary ApiCall fn',
+          error
+        })
+        throw err
+      }
+    }).then((result) => {
       this.result = result
```
[the remark this answers is not in the document]
Comment (SgtPooki) [reply src/ApiCall.ts:98]: I was looking for a good deferred library for this use-case and ended up just working around it. I don't like that the js ecosystem considers `deferred` an anti-pattern.. but w/e. It *shouldn't* be accessed elsewhere prior to this, and I could had an exception via proxy/getter to ensure as much during runtime. 

If you search the code for uses of `.result` there are zero results outside of the property declaration and these lines:
image

The uses of ApiCall.result are in the expectation callbacks:
image

Which begs the question, why is the property public? I'll update it.

[the remark this answers is not in the document]
Comment (achingbrain) [reply src/ApiCall.ts:98]: > I don't like that the js ecosystem considers deferred an anti-pattern

There's an interesting thread about that here, lots of good links in the replies - https://twitter.com/matteocollina/status/1502329506333396997

[the remark this answers is not in the document]
Comment (SgtPooki) [reply src/ApiCall.ts:98]: I added in pDefer to help with ordering of expectation running, but I'll leave result as it is for now. changes coming up now
